### ISSUE TITLE
pod install fails

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [FancyPixel/gulps#1]
I have CocoaPods 0.36.4, the latest version as of today installed. I cloned this project and ran `pod install` but I get the following error.

![screen shot 2015-04-21 at 12 02 03 am](https://cloud.githubusercontent.com/assets/2551877/7237521/b2e81e78-e7b9-11e4-9bc7-9f913699e8e2.png)

**Comment by andreamazz** [comment]
Hi @Isuru-Nanayakkara 
My bad, I was pointing to the wrong endpoint, checkout latest commit for an updated Podfile. 

Cheers
