### ISSUE TITLE
xcode issure/failure

### ISSUE THREAD

**Issue by andyferriby** [FancyPixel/gulps#16]
Hi, opened the xcode project and it fails trying to build for iphone simulator.

This is the 2 errors:

<a href='http://postimg.org/image/krtfft9vl/' target='_blank'><img src='http://s16.postimg.org/krtfft9vl/Screen_Shot_2016_09_24_at_12_44_23.png' border='0' alt='postimage'/></a>

Many Thanks,

Andrew :-)

**Comment by andreamazz** [comment]
Hi @andyferriby 
The project currently needs to be run with swift 2.2.
I'll work on the swift 3 version soon though.

cheers

**Comment by andyferriby** [comment]
Sweet thanks mate.... got a pdd problem with it at the moment... got it all working and ive got a developer account but for some odd reason when archiving it, im getting the attachdd pic even tho all my provisioning profiles are installed! All my app ids are all part of a group in my developer account as well[Image]

Get Outlook for iOS<https://aka.ms/o0ukef>




On Mon, Sep 26, 2016 at 3:03 PM +0100, "Andrea Mazzini" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @andyferriby<https://github.com/andyferriby>
The project currently needs to be run with swift 2.2.
I'll work on the swift 3 version soon though.

cheers

-

**Comment by andyferriby** [comment]
Check dependencies

Code Sign error: No matching provisioning profiles found: None of the valid provisioning profiles allowed the specified entitlements: com.apple.security.application-groups.

**Comment by andreamazz** [comment]
Updated to swift 3.
As for publishing the same app with your own name: please fucking don't.

**Comment by andyferriby** [comment]
have a look on the app store your self, someone else is selling your app on there
