### ISSUE TITLE
Errors while uploading to itunes via xcode

### ISSUE THREAD

**Issue by andyferriby** [FancyPixel/gulps#17]
Hi, got a problem with an ios app while trying to submit to the app store using xcode upload to app store.

Error ITMS-90045
Error ITMS-90205
Error ITMS-09206

Everything is set up in my itunes connect and so on but when i go to upload i get the above errors
Screen shot is here:
https://postimg.org/image/sq4qr3bwj/

Many Thanks

**Comment by andreamazz** [comment]
Can't help but wonder why on earth would you submit this to the store.

**Comment by andyferriby** [comment]
no orrence, but theres a few of your apps on the app store so why have a go and say its not to go on the store?


________________________________

**Comment by andreamazz** [comment]
You are asking me "if the world is full of assholes, why shouldn't I be one?"
Do I really have to answer?

**Comment by andyferriby** [comment]
Your answer is clear in your statement below:


And also stop using bad language...Or you will be reported


Copyright (c) 2015 Fancy Pixel S.r.l. All rights reserved.

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the "Software"),
to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:



________________________________

**Comment by andreamazz** [comment]
It's always sad to see people with no moral compass. 
Cheers
